%YAML 1.1
---

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"

default-rule-path: /etc/suricata/rules

rule-files:
  - custom-sip.rules

# Activar análisis SIP en capa de aplicación
app-layer:
  protocols:
    sip:
      enabled: yes

outputs:
  - fast:
      enabled: yes
      filename: fast.log
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            tagged-packets: yes
        - http
        - dns
        - tls
        - sip  # ya estaba incluido, bien hecho

af-packet:
  - interface: eno2
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes

logging:
  default-log-level: info
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        filename: /var/log/suricata/suricata.log

