services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  suricata:
    image: jasonish/suricata:latest
    command: -i eno2 -c /etc/suricata/suricata.yaml -v
    volumes:
      - ./suricata-config/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./suricata-rules:/etc/suricata/rules:ro
      - ./logs:/var/log/suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

  suricata-redis-anomaly:
    image: python:3.9-slim
    volumes:
      - ./suricata-config:/app
      - ./logs:/logs
    working_dir: /app
    command: python3 suricata_redis_anomaly.py
    depends_on:
      - redis
      - suricata

volumes:
  redis_data:

